stages:
  prepare_fireball:
    cmd: python scripts/fireball/1_fireball_preprocessing.py
    deps:
    - data/fireball
    - scripts/fireball/1_fireball_preprocessing.py
    outs:
    - data/fireball_postprocessed/
  tokenize_fireball:
    cmd: python scripts/fireball/2_prepare_fireball_for_training.py
    deps:
    - data/fireball_postprocessed/
    - scripts/fireball/2_prepare_fireball_for_training.py
    outs:
    - data/fireball_tokenized
